app/authers/models.py
from .. models import db
from app.models import db


class Author(db.Model):
    __tablename__ = 'author'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    books = db.relationship('Book', backref='author', lazy=True)

    def __str__(self):
        return f"{self.name}"

    @classmethod
    def authers(cls):
        return cls.query.all()

app/books/models.py
from .. models import db
from app.models import db
from datetime import datetime


class Book(db.Model):
    __tablename__ = 'book'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, nullable=False)
    description = db.Column(db.String, nullable=True)
    rate = db.Column(db.Integer, default=4, nullable=True)
    image = db.Column(db.String(300))
    created = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated = db.Column(db.DateTime, onupdate=datetime.utcnow)
    author_id = db.Column(
        db.Integer, db.ForeignKey('author.id'), nullable=True)

    def __str__(self):
        return f"{self.title}"

    @classmethod
    def get_all_Books(cls):
        return cls.query.all()

    @classmethod
    def get_specific_book(cls, id):
        return cls.query.get(id)

    def delete_book(self):
        db.session.delete(self)
        db.session.commit()
        return True

    @classmethod
    def create_newBook(cls, book_new_obj):
        # newBook = cls(**book_new_obj)
        db.session.add(book_new_obj)
        db.session.commit()
        return book_new_obj

    @classmethod
    def delete_Book(cls, book_new_obj):
        # newBook = cls(**book_new_obj)
        db.session.delete(book_new_obj)
        db.session.commit()
        return True

    def update_book(self, updated_data):
        """  
         db.session.add(self)
         db.session.commit()
         return True

        """
        pass

app/models.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

app/__init__.py
from flask import Flask
from flask_migrate import Migrate

from app.models import db

from app.config import projectConfig as appConfig  # dic -> of dev&prd mood
from app.books.models import Book

from app.authers.models import Author

# import configration -> spesify wither u r in production in dev mood ->.


def create_app(config_name):
    app = Flask(__name__)

    current_config = appConfig[config_name]  # class
    app.config['SQLALCHEMY_DATABASE_URI'] = current_config.SQLALCHEMY_DATABASE_URI
    # search in this class about class variable with this name
    app.config['SQLALCHEMY_DATABASE_URI'] = current_config

    app.config.from_object(current_config)  # read configration
    db.init_app(app)  # initalize app
    # add migration
    migrate = Migrate(app, db)

    # register blueprint

    from app.books import books_blueprint
    # from app.authers import auths_blueprint
    app.register_blueprint(books_blueprint)
    # app.register_blueprint(auths_blueprint)
    # route of books
    # from app.books.views import home, get_books, bookDetail
    # app.add_url_rule('/', view_func=home)
    # app.add_url_rule('/lst_books', view_func=get_books)
    # app.add_url_rule('/oneBook/<id>', view_func=bookDetail)

    from app.books.errors import error_view
    # app.error("/notFound", view_func=error_view)
    app.register_error_handler(404, error_view)
    return app

app/authers/__init__.py
from flask import Blueprint

auth_blueprint = Blueprint('auth', __name__, url_prefix='/auth')
from app.authers import views

app/authers/views.py
# @app.route("/books", endpoint="lst_books")
from flask import render_template

from app.authers import auth_blueprint

# <a href={{url_for("deleteBook" , id=book.id)}} class="buy">Delete Bppk</a>


""" 

def get_books():
    books = Books.query.all()
    return render_template("lst_books.html", books=books)


def bookDetail(id):
    print(id)
    book = Books.query.get(id)
    return render_template("bookDetails.html", book=book)
 """

app/books/__init__.py
from flask import Blueprint


books_blueprint = Blueprint('books', __name__, url_prefix='/book')
from app.books import views

app/books/api/views.py
from flask_restful import Resource, Api, marshal_with, abort
from app.books.models import Book
from app.books.api.serializers import Bookerilizer
from app.books.api.parser import bookparser
from app.models import db

from app.books.models import Book

class lstBook(Resource):
    @marshal_with(Bookerilizer)
    def get(self):
        books = Book.get_all_Books()
        return books

    @marshal_with(Bookerilizer)
    def post(self):
        Book = bookparser.parse_args()
        newBook = Book(**Book)
        db.session.add(newBook)
        db.session.commit()
        return newBook, 201


class PostGetSpecificAndUpdateAndDelete(Resource):
    @marshal_with(Bookerilizer)
    def get(self, id):
        book = Book.get_specific_book(id)
        if book:
            return book, 200

        return abort(404, message="book not found")

    @marshal_with(Bookerilizer)
    def put(self, id):
        book = Book.query.get(id)
        if book:
            post_args = bookparser.parse_args()
            book.update_post(post_args)
            return book, 200

        return abort(205, message="book not found")

    def delete(self, id):
        book = Book.get_specific_book(id)
        if book:
            book.delete_book()
            return {"deleted": "book Deleted"}
        return 'page not found ',404 

app/books/views.py
from ..books.BookForm import BookForm
from .models import Book
from flask import render_template, redirect, request, jsonify
# <a href={{url_for("deleteBook" , id=book.id)}} class="buy">Delete Bppk</a>
# from app.books import books_blueprint

from app.books import books_blueprint

from app.authers.models import Author


@books_blueprint.route("/", endpoint="home")
def home():
    return render_template("index.html")


@books_blueprint.route("/lst_books", endpoint="get_books")
def get_books():
    books = Book.query.all()
    return render_template("lst_books.html", books=books)


@books_blueprint.route("oneBook/<id>", endpoint="bookDetail")
def bookDetail(id):
    print(id)
    book = Book.query.get(id)
    return render_template("bookDetails.html", book=book)


@books_blueprint.route("delete/<id>", endpoint="delete_book")
def bookDetail(id):
    print(id)
    print("---------------")

    book = Book.query.get(id)
    Book.delete_Book(book)
    print("---------------")
    return redirect("get_books")


@books_blueprint.route('/createBook', methods=['POST', 'GET'], endpoint="create_new_book")
def addNewPost():
    form = BookForm()
    authers = Author.query.all()
    print("--------------------", authers)
    if request.method == 'GET':
        return render_template("create.html", form=form, authers=authers)
    if request.method == 'POST':
        newBook = Book()
        newBook.title = request.form['title']
        newBook.description = request.form['description']
        newBook.image = request.form['image']
        newBook.rate = request.form['rate']
        # newBook.author_id = request.form['auth']

        Book.create_newBook(newBook)
        return redirect('lst_books')


@books_blueprint.route('/update/<int:id>/', methods=('GET', 'POST'), endpoint="update_book")
def update(id):
    form = Book.query.get_or_404(id)
    authers = Author.query.all()

    if request.method == 'GET':
        return render_template('create.html', form=form, authers=authers)
    if request.method == 'POST':
        title = request.form['title']
        # title = request.form.get('title')
        if title is None:
            return jsonify({'error': 'Title is missing'}), 400

        editBook = Book(**request.form)
        Book.create_newBook(editBook)
        return redirect('get_books')

app/templates/BooksMacro.html
{% macro books_macro(books)%}
{% for book in books %}

<div class="card text-center col-md-4 mt-3 m-2 col-sm-6 p-0">
  <div class="card-header p-0">
  
    <img  class="img-fluid" src="{{ url_for('static', filename = 'images/'+book.image) }}" alt="">
  </div>
  <div class="card-body">
    <h5 class="card-title">{{book['title']}}
    </h5>
    <p class="card-text"> Book Auther : {{book.author}}</p>
    <button class="btn btn-outline-info" >
      <a href={{url_for("books.bookDetail" , id=book.id)}} class="buy">view book</a>
    </button>
    <button class="btn btn-outline-danger" >
      <a href={{url_for("books.delete_book" , id=book.id)}} class="buy ">delete book  -> {{book.id}}</a>
    </button>
    <button class="btn btn-outline-danger" >
      <a href={{url_for("books.update_book" , id=book.id)}} class="buy ">update book  -> {{book.id}}</a>
    </button>
  </div>
  
  
      
  <div class="card-footer text-muted">
   {{book.created}}
  </div>
</div>
{% endfor %}
{%endmacro%}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book Store</title>
    <link rel="stylesheet" {{ url_for('static', filename='css/style.css') }} />
    <link rel="stylesheet" {{ url_for('static', filename='css/book.css') }} />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    {% include "includes/navbar.html"  %}

    <div class="container">
    {% block content %}
    {% endblock%}

    <div class="fs-2 m-5">
        {% block productview %}

        {% endblock %}
    </div>
    <div class="fs-2 m-5">
        {% block main %}

        {% endblock %}
    </div>
   


    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

app/templates/bookDetails.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book Details</title>
    <link rel="stylesheet" {{ url_for('static', filename='css/book.css') }} />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    {% include "includes/navbar.html"  %}
    
    <div class="card m-5 ">
      <div class="row">
  
        <div class="img-container col-5 ">
          
              <img class="phone"   src="{{ url_for('static', filename = 'images/'+book.image) }}" 
              alt="book img">
              
        </div>
  
        <div class="col-7 ">
          <div class="container m-4">
            <h1>{{book.title}}</h1>
            {{book.image}}
            <p class="card-text">{{book.description}}</p>
            <p class="card-text"> Book Rate : {{book.rate}}</p>
            <p class="card-text"> Book Auther : {{book.author}}</p>
            <a href={{url_for("books.get_books")}} class="buy btn btn-info">Back Home</a>

          </div>
        
        </div>
  </div>

</body>

app/templates/create.html
{% extends 'base.html' %}
{% block main %}

<div>
    <form method="POST">
        {{form.csrf_token}}
        <div class="mb-3">
            <div class="form-label"> {{form.title.label}} </div>
            {{form.title(size=20, value=title, class='form-control')}}

            <p class="text-danger"> {% if errors and errors['title'] %}
                {{errors['title']}} {%endif%}
            </p>

        </div>
        <div class="mb-3">
            <div class="form-label"> {{form.description.label}} </div>
            {{form.description( value=description, class='form-control')}}

        </div>

        <div class="mb-3">

            <div class="mb-3" class="form-label"> {{form.rate.label}}
                {{form.rate( value=rate, class='')}}
            </div>

        </div>
        <div class="mb-3">
            <div class="form-label"> {{form.image.label}} </div>
            {{form.image( value=image, class='form-control', value=age )}}
        </div>

        <select id="colors" name="colors">
            <option value="red">red color</option>
            {%for auth in authers%}
            
            <option value={{auth.id}}>{{auth.name}}</option>
            {%endfor%}
        </select>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

</div>

{% endblock %}

app/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark px-0 py-3">
    <div class="container-xl">
        <!-- Logo -->
        <a class="navbar-brand" >
            <img src="https://preview.webpixels.io/web/img/logos/clever-light.svg" class="h-8" alt="...">
        </a>
        <!-- Navbar toggle -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <!-- Nav get_cats -->
            <div class="navbar-nav mx-lg-auto">
               <a class="nav-item nav-link active" 
               href={{url_for("books.home" )}} 
               aria-current="page">Home</a>
                <a class="nav-item nav-link"
                href={{url_for("books.get_books")}}
                
                 >Books</a>
                
            </div>
          
                 

           
            <!-- Action -->
             
        </div>
    </div>
</nav>

app/templates/index.html
{% extends 'base.html' %}

{% block main %}
<!--MAIN-->
<main class="hero">
    <section class="text-center hero">
        <em>Eco friendly</em>
        <em>Voala {{name}}</em>
        <h1 class="title m-5">We like to think of our wares as full sensory experiences!</h1>
        <a  class="btn1 btn btn-outline-info  qm-5" href="{{url_for("books.home" , name="dana")}}">Get Start </a>
    </section>
</main>
{% endblock %}

app/templates/lst_books.html
{% extends 'base.html' %}

{% block main %}
<div class="row">
    
<button class="btn btn-outline-info" >
    <a href={{url_for("books.create_new_book")}} class="buy">Create New Book</a>

</button>

{%import 'BooksMacro.html' as lst_books%}
    {{lst_books.books_macro(books)}}

</div>
{% endblock %}